# Generated by Django 4.2.6 on 2024-08-18 15:05

from django.db import migrations, models
import restaurant.models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='timeoforder',
            field=models.TimeField(default=restaurant.models.current_time),
        ),
    ]
