# Generated by Django 4.2.6 on 2024-08-18 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_order_timeoforder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='timeoforder',
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(db_index=True),
        ),
    ]
