# Generated by Django 4.2.6 on 2024-08-19 03:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0006_alter_order_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='timeoforder',
            field=models.TimeField(default=datetime.time(11, 18, 45, 157811)),
        ),
    ]
