# Generated by Django 4.2.6 on 2024-08-19 03:25

from django.db import migrations, models
import restaurant.models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0007_order_timeoforder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='timeoforder',
            field=models.TimeField(default=restaurant.models.currenttime),
        ),
    ]
