# Generated by Django 4.2.6 on 2024-08-19 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0008_alter_order_timeoforder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_status',
            field=models.CharField(db_index=True, default='Your order has been received. You will receive an update when our chefs begin preparing your items.', max_length=255),
        ),
    ]
