# Generated by Django 4.2.6 on 2024-08-19 06:10

from django.db import migrations, models
import restaurant.models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0009_alter_order_delivery_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='item_updated_at',
            field=models.TimeField(default=restaurant.models.currenttime),
        ),
    ]
